#!/bin/sh

# Get a list of all Python files that are staged for commit
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

# Exit if there are no Python files
if [ -z "$files" ]; then
    exit 0
fi

# Run autopep8 on each file
for file in $files; do
    autopep8 --in-place --aggressive --aggressive "$file"
    # Add the file back to the staging area
    git add "$file"
done

# Exit with 0 to allow the commit to proceed
exit 0